<?php

namespace AppBundle\Repository;

/**
 * mensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mensajeRepository extends \Doctrine\ORM\EntityRepository
{
}
